### ISSUE TITLE
unrecognized option '--force'

### ISSUE THREAD

**Issue by krupan** [gh2o/digitalocean-debian-to-arch#83] opened 2019-12-07 19:59 UTC
I just ran this on a Debian 9 droplet that I created today and I got an error when it got to this line:

    local chroot_pacman="chroot /d2a/work/archroot pacman --arch ${target_architecture} --force"

I removed the `--force` and ran again and it seems to be proceeding fine now.

**Comment by z3ntu** [comment] 2019-12-08 16:39
You can try #82, that should fix this issue. (and this is a duplicate of #81)

**Comment by krupan** [comment] 2019-12-08 17:51
#82 did fix the problem. Thanks!

**Comment by gh2o** [comment] 2020-01-09 08:19
Should be fixed in #82

**Closed as completed by gh2o** 2020-01-09 08:19 UTC
